apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: myconregistrydemo.azurecr.io/nginx:v1
        imagePullPolicy: IfNotPresent
      imagePullSecrets:
        - name: acr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: myapp-service  # Name of the service
spec:
  selector:
    app: myapp  # This should match the label in the deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer 
