name: CI/CD PIPELINE
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: containernginx.azurecr.io
        username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
        password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}
    - name: Build and push Docker image
      run: |
        IMAGE_NAME=containernginx.azurecr.io/nginx
        IMAGE_TAG=latest
        echo "Building Docker image..."
        # Ensure Dockerfile exists
        if [ ! -f nginx.dockerfile ]; then
          echo "Error: nginx.dockerfile not found!"
          exit 1
        fi
        # Run the build command correctly
        docker build -t $IMAGE_NAME:$IMAGE_TAG -f ./nginx.dockerfile .
        echo "Pushing Docker image to ACR..."
        docker push $IMAGE_NAME:$IMAGE_TAG
    - name: Logout from Azure Container Registry
      run: docker logout containernginx.azurecr.io
